Check for curl and jq when running boat auth
boat auth is possible one of the first commands being run by a new user,
needs to make sure that curl and jq is available.

diff --git a/bin/auth b/bin/auth
--- a/bin/auth
+++ b/bin/auth
@@ -1,5 +1,30 @@
 #!/usr/bin/env bash
 
+# Check for curl
+command -v curl > /dev/null
+if [ $? -eq 0 ]; then
+  CURL_VERSION=`curl --version | head -1 | awk '{print $2}'`
+  if ! version_gt ${CURL_VERSION} 7.55.0; then
+    error "curl v7.55.0 or greater is required, but found v${CURL_VERSION}"
+    space "Read more in FIXME: Link to docs"
+    exit 1
+  fi
+else
+  error "curl command not found!"
+  space "curl is required for running the Longboat CLI tools."
+  space "Read more on FIXME: Link to docs"
+  exit 1
+fi
+
+# Check for jq
+command -v jq > /dev/null
+if [ $? -ne 0 ]; then
+  error "jq command not found!"
+  space "jq is required for running the Longboat CLI tools."
+  space "Please install jq: FIXME: Link to docs"
+  exit 1
+fi
+
 if [ -z "${LONGBOAT_TOKEN}" ]; then
   if [ -f "${USERCONFIG}" ]; then
     echo ""
