Adding option to allow custom commands to be run before ansible
This allows people to make sure python is installed etc. allowing for a
smooth ansible ride.

diff --git a/bin/droplet b/bin/droplet
--- a/bin/droplet
+++ b/bin/droplet
@@ -165,9 +165,14 @@ case "${ARGUMENT}" in
     exit 1
   fi
 
-  # FIXME: Plain SSH to droplet and make sure python is installed
-  # FIXME: Only tested with Ubuntu 16.04 (hence python interpreter issue)
-  # FIXME: Setting a different python interpreter might be a tricky solution - it should either be permanent or easy changeable :/
+  if [ ! -z "${LONGBOAT_BOOTSTRAP_COMMAND}" ] ; then
+    info "Running custom bootstrap command on ${BLUE}${HOST_NAME}${NC}"
+    # shellcheck disable=SC2029
+    if ! OUTPUT=$(ssh "root@${DROPLET_IPV4}" "${LONGBOAT_BOOTSTRAP_COMMAND}" 2>&1) ; then
+      echo "${OUTPUT}" > ./bootstrap-command-error.log
+      error "Custom command failed. Output saved to: ${BLUE}./bootstrap-command-error.log${NC}"
+    fi
+  fi
 
   info "Running ${BLUE}ansible-playbook ${LONGBOAT_BOOTSTRAP_PLAYBOOK}${NC} on ${BLUE}${HOST_NAME}${NC}"
 
@@ -175,15 +180,11 @@ case "${ARGUMENT}" in
     --inventory="${HOST_ENV}" \
     --limit="${HOST_SHORT}.${HOST_ENV}" \
     --extra-vars="ansible_host=${DROPLET_IPV4}" \
-    --extra-vars="ansible_user=root" \
-    --extra-vars="ansible_python_interpreter=/usr/bin/python3") ; then
-    echo "${PLAYBOOK}" > ./bootstrap-playbook.log
-    error "ansible-playbook run failed - output saved to: ${BLUE}./bootstrap-playbook.log${NC}"
+    --extra-vars="ansible_user=root") ; then
+    echo "${PLAYBOOK}" > ./bootstrap-playbook-error.log
+    error "ansible-playbook run failed - output saved to: ${BLUE}./bootstrap-playbook-error.log${NC}"
     exit 1
   fi
-
-  #FIXME: Request Longboat: update host set status :managed
-
   ;;
 
 *)
