Host command to add host keys to a host

diff --git a/bin/host b/bin/host
--- a/bin/host
+++ b/bin/host
@@ -22,6 +22,48 @@ case "${ARGUMENT}" in
   user_hosts_update
   ;;
 
+"keys")
+  CURL_SILENT=true
+  CURL_CONTINUE=true
+  api_curl GET /hosts/name/$3 project_id=${LONGBOAT_PROJECT} environment_name=$4
+  if [ "${CURL_CODE}" == "200" ]; then
+    ID=`echo "${CURL_RESPONSE}" | jq -r '.["id"]'`
+    FQDN=`echo "${CURL_RESPONSE}" | jq -r '.["fqdn"]'`
+
+    if [ "${FQDN}" == "null" ]; then
+      echo "ERROR: FQDN is not set for this host."
+      exit 1
+    fi
+
+    echo "==> Scanning host ${FQDN} - this might take a little while..."
+    KEYS=`ssh-keyscan ${FQDN} 2> /dev/null`
+
+    if [ -z "${KEYS}" ]; then
+      echo "ERROR: No keys returned by: ssh-keyscan ${FQDN}"
+      exit 1
+    fi
+
+    echo "==> ssh-keyscan returned this:"
+    echo "${KEYS}"
+    echo -n "==> Add the keys? (y/N) "
+    confirm_continue
+
+    TMPFILE="/tmp/longboat.hostkeys.$$"
+    echo "${KEYS}" > ${TMPFILE}
+    api_curl POST /hosts/${ID}/keys hostkeys@${TMPFILE}
+    rm ${TMPFILE}
+    if [ "${CURL_CODE}" == "200" ]; then
+      echo "Success - host keys added."
+    else
+      echo_json "${CURL_RESPONSE}"
+      exit 1
+    fi
+  else
+    echo_json "${CURL_RESPONSE}"
+    exit 1
+  fi
+  ;;
+
 "delete")
   api_curl GET /hosts/$3
   if [ "${CURL_CODE}" == "200" ]; then
diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -47,6 +47,14 @@ function api_curl() {
   fi
 }
 
+function confirm_continue() {
+  read CONFIRM
+  if [ "${CONFIRM}" != "y" ]; then
+    echo "aborted."
+    exit 1
+  fi
+}
+
 function confirm_delete() {
   local METHOD="$1"
   local URL="$2"
